language: php
sudo: false
php:
    - 5.6.18

notifications:
    email:
        recipients:
            - david.bittner@seznam.cz

before_script: 
    - curl -s -o $HOME/.phpenv/versions/5.6/bin/phpunit https://phar.phpunit.de/phpunit.phar
    - chmod +x $HOME/.phpenv/versions/5.6/bin/phpunit
    - composer install
script: phpunit
