language: php
sudo: false
php:
    - 5.6.18

notifications:
    email:
        recipients:
            - david.bittner@seznam.cz

before_script: 
    - composer install

script: ./vendor/bin/phpunit
