language: php
dist: trusty
sudo: required
php:
    - 5.6.18

services:
    - mysql
    
env:
    - TESTHOST=localhost TESTDB=schemabuilder_tests TESTUSER=root

notifications:
    email:
        recipients:
            - david.bittner@seznam.cz

before_script: 
    - mysql -e 'CREATE DATABASE schemabuilder_tests;'
    - composer install

script: ./vendor/bin/phpunit -v
